### ISSUE TITLE
Alexa no longer working for cover

### ISSUE THREAD

**Issue by finity69x2** [auchter/haaska#113]
I have a defined garage door cover component:

```
- platform: template
    covers:
      north_garage_door:
        friendly_name: 'North Garage Door'
        value_template: "{{ is_state('binary_sensor.garage_door_north_position_sensor', 'on') }}"
        open_cover:
          service: script.turn_on
          entity_id: script.open_gdn
        close_cover:
          service: script.turn_on
          entity_id: script.close_gdn
        stop_cover:
          service: switch.turn_on
          entity_id: switch.garage_door_north_operator_switch
        icon_template: "{% if not is_state('binary_sensor.garage_door_north_position_sensor', 'off') %}mdi:garage-open{% else %}mdi:garage{% endif %}"
```

it is exposed to the Echo using Haaska.

it is being seen in the Alexa app as a "home assistant cover"

But when I tell Alexa to “open” or “close” the north garage door, it replies with “north garage door doesn’t support that”.

All of the other devices exposed thru haaska still work.

I tried to hide it from haaska and expose it thru emulated_hue and then it gets seen as a “dimmable light” and i get the same response from Alexa.

Am I missing something? I thought that this worked at one time.

Any help at all would be appreciated.
